#!/usr/bin/env bash

shopt -s globstar

PROJECT_ROOT=`git rev-parse --show-toplevel`
cd "${PROJECT_ROOT}"

for file in **/*.{c,cc,cpp,h,hh,hpp}; do
    [[ ! -e $file ]] && continue

    echo "Formatting ${file}"
    clang-format -i -style=file ${file}
    git add ${file}
done

cd -
